name: CI

on: 
  push:
  pull_request:
  release:
    types: [published]
  
env:
  vcpkg_TAG: 5852144908b2c714be6f0d343f1de01ca2ec7758

jobs:
  build:
    # We would like to build with v140 toolset to be compatible with both VS2017, 2019
    # But that will only be avaiilable in late november: https://github.com/actions/virtual-environments/issues/68  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1
    
    - name: Check free space 
      shell: bash 
      run: |
        df -h
  
    # Workaround for https://github.community/t5/GitHub-Actions/Windows-tests-worked-yesterday-broken-today/td-p/43574
    - name: Override bash shell PATH (windows-latest)
      run: echo "::add-path::C:\Program Files\Git\bin"
    
    - name: Download custom vcpkg and additional ports 
      shell: bash
      run: |
        choco install -y wget
        mkdir C:/ify-deps
        cd C:/ify-deps
        cd /c/ify-deps
        git clone https://github.com/Microsoft/vcpkg
        cd vcpkg
        git checkout ${vcpkg_TAG}
        ./bootstrap-vcpkg.sh
        
    - name: Install vcpkg ports
      shell: bash
      run: |
        /c/ify-deps/vcpkg/vcpkg.exe install --triplet x64-windows-static catch2 qt5-base[latest]

    # Remove temporary files https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-can-i-remove-temporary-files
    # For some reason doing using git bash to do rm -rf fails for icu's port buildtrees, probably for the use of msys2 
    # See https://github.com/microsoft/vcpkg/issues/10365  
    - name: Cleanup vcpkg temporary directories
      shell: cmd 
      run: |
        RMDIR /Q/S C:\ify-deps\vcpkg\buildtrees
        RMDIR /Q/S C:\ify-deps\vcpkg\packages
        RMDIR /Q/S C:\ify-deps\vcpkg\downloads

    - name: Prepare release file
      if: github.event_name == 'release'
      shell: cmd 
      run: |
        7z a ify-deps-x64-windows-static.zip C:\ify-deps
        
    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./ify-deps-x64-windows-static.zip
          asset_name: ify-deps-x64-windows-static.zip
          asset_content_type: application/zip
